/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-08-19 03:06:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.v1;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class Read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head><title>JSPBoard</title>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");

	String b_num = request.getParameter("b_num");
	
	Connection con = null;
	Statement stmt = null;
	ResultSet rs = null;
	
	String content="", name="", regdate="", email="", homepage="", subject="",
			ip="";
	int count = 0;
	try{
		Class.forName("com.mysql.jdbc.Driver");
		String url = "jdbc:mysql://localhost:3306/jspdb";
		con = DriverManager.getConnection(url, "root", "1111");
		
		String sql = "select * from tblboard where b_num=" + b_num;
		stmt = con.createStatement();
		rs = stmt.executeQuery(sql);
		
		if(rs.next()) {
			name = rs.getString("b_name");
			regdate = rs.getString("b_regdate");
			email = rs.getString("b_email");
			homepage = rs.getString("b_homepage");
			subject = rs.getString("b_subject");
			content = rs.getString("b_content");
			ip = rs.getString("b_ip");
			count = rs.getInt("b_count");
		}
		count++;
		
		sql = "update tblboard set b_count=" + count + " where b_num=" + b_num;
		stmt.executeUpdate(sql);
		
	} catch(Exception err) {
		err.printStackTrace();
	} finally {
		if(con!= null){con.close();}
		if(stmt != null) { stmt.close(); }
		if(rs != null) { rs.close(); }
	}

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<br><br>\r\n");
      out.write("<table align=center width=70% border=0 cellspacing=3 cellpadding=0>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td bgcolor=9CA2EE height=25 align=center class=m>글읽기</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td colspan=2>\r\n");
      out.write("   <table border=0 cellpadding=3 cellspacing=0 width=100%> \r\n");
      out.write("    <tr> \r\n");
      out.write("\t <td align=center bgcolor=#dddddd width=10%> 이 름 </td>\r\n");
      out.write("\t <td bgcolor=#ffffe8>");
      out.print(name );
      out.write("</td>\r\n");
      out.write("\t <td align=center bgcolor=#dddddd width=10%> 등록날짜 </td>\r\n");
      out.write("\t <td bgcolor=#ffffe8>");
      out.print(regdate );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("\t <td align=center bgcolor=#dddddd width=10%> 메 일 </td>\r\n");
      out.write("\t <td bgcolor=#ffffe8 >");
      out.print(email );
      out.write("</td> \r\n");
      out.write("\t <td align=center bgcolor=#dddddd width=10%> 홈페이지 </td>\r\n");
      out.write("\t <td bgcolor=#ffffe8 ><a href=\"http://");
      out.print(homepage );
      out.write("\" target=\"_new\">http://");
      out.print(homepage );
      out.write("</a></td> \r\n");
      out.write("\t</tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("     <td align=center bgcolor=#dddddd> 제 목</td>\r\n");
      out.write("     <td bgcolor=#ffffe8 colspan=3>");
      out.print(subject );
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr> \r\n");
      out.write("    <td colspan=4>");
      out.print(content.replace("\n", "<br>"));
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td colspan=4 align=right>\r\n");
      out.write("    ");
      out.print(ip );
      out.write(" 로 부터 글을 남기셨습니다./  조회수 :");
      out.print(count );
      out.write(" \r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("  <td align=center colspan=2> \r\n");
      out.write("\t<hr size=1>\r\n");
      out.write("\t[ <a href=\"javascript:list()\">목 록</a> | \r\n");
      out.write("\t<a href=\"Update.jsp?b_num=");
      out.print(b_num);
      out.write("\">수 정</a> |\r\n");
      out.write("\t<a href=\"Delete.jsp?b_num=");
      out.print(b_num);
      out.write("\">삭 제</a> ]<br>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
